export default {
    JOIN: 'join',
    JOINED: 'joined',
    DISCONNECTED: 'disconnected',
    CODE_CHANGE: 'code-change',
    LANGUAGE_CHANGE: 'language-change',
    UPDATE_LANGUAGE: 'language-update',
    INPUT_CHANGE: 'input-change',
    UPDATE_INPUT: 'input-update',
    LEAVE: 'leave',
    SEND_MESSAGE: 'send-message',
    RECEIVE_MESSAGE: 'receive-message',
    INPUT_CHANGE: 'input-change',
    OUTPUT_CHANGE: 'output-change',
    ROOM_MEMBERS: 'room-members',
};
